### ISSUE TITLE
warning! CG_CONTEXT_SHOW_BACKTRACE environmental variable

### ISSUE THREAD

**Issue by syedrazackimran** [jamesdouble/JDProgressRoundView#4]
i don't know how to fix this warning!!  please set CG_CONTEXT_SHOW_BACKTRACE environmental variable
<img width="1325" alt="screen shot 2017-07-14 at 9 08 47 pm" src="https://user-images.githubusercontent.com/15051045/28215552-a83ad2c0-68d8-11e7-8c20-75dff109962d.png">
 . kindly fix it !

**Comment by jamesdouble** [comment]
Hi, @syedrazackimran , thanks for your feedback.
May I ask you whether  this warning cause a crash or not

**Comment by syedrazackimran** [comment]
No, it doesn't but! I feel may be a memory warning will come! so only!  I asked to fix that issues I tried to fix but I didn't find solution kindly do needful

**Comment by jamesdouble** [comment]
I have made a new commit,
Check if problem been solved

**Comment by syedrazackimran** [comment]
JDProgressRoundView (2.1.0) in update you pod file still I'm facing the same issue! pls kindly do needful  !!

**Comment by jamesdouble** [comment]
I'm not update Pod yet.
So you may need to download the repo which commit after #5 .

**Comment by syedrazackimran** [comment]
Awesome bro. it's superb !! it works fine !!

**Comment by jamesdouble** [comment]
Thanks for using & feedback.

**Comment by syedrazackimran** [comment]
hi Sorry!
Still, it's not resolved I'm still getting those warnings!

**Comment by jamesdouble** [comment]
@syedrazackimran  which type of Progress do you use?

**Comment by syedrazackimran** [comment]
water type !! 
<img width="1440" alt="screen shot 2017-08-03 at 1 18 52 pm" src="https://user-images.githubusercontent.com/15051045/28908540-7132665a-784e-11e7-9aeb-258940fdceca.png">


I add UI Design Screen shot kindly check it!

**Comment by jamesdouble** [comment]
Check commit [840b0cb](https://github.com/jamesdouble/JDProgressRoundView/commit/840b0cb126823272bdb14142a990de78426b3ac4)
